<a href="https://colab.research.google.com/github/aditi91999/LeetCode-Feedback/blob/master/SentimentalAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [6]:
!pip install scikit-learn

In [7]:
!pip install -U spacy

     |████████████████████████████████| 12.8MB 275kB/s 
     |████████████████████████████████| 9.1MB 28.4MB/s 
     |████████████████████████████████| 460kB 38.1MB/s 
     |████████████████████████████████| 1.1MB 38.1MB/s 
     |████████████████████████████████| 122kB 35.2MB/s 
  Created wheel for smart-open: filename=smart_open-3.0.0-cp37-none-any.whl size=107098 sha256=73ee8bccebfa2b7dfdd26b07638651191ef193841969278dd8bd2f2344f941c5
  Stored in directory: /root/.cache/pip/wheels/18/88/7c/f06dabd5e9cabe02d2269167bcacbbf9b47d0c0ff7d6ebcb78
Successfully built smart-open
  Found existing installation: smart-open 4.2.0
    Uninstalling smart-open-4.2.0:
      Successfully uninstalled smart-open-4.2.0
  Found existing installation: catalogue 1.0.0
    Uninstalling catalogue-1.0.0:
      Successfully uninstalled catalogue-1.0.0
  Found existing installation: srsly 1.0.5
    Uninstalling srsly-1.0.5:
      Successfully uninstalled srsly-1.0.5
  Found existing installation: thinc 7.4.0
    U

In [8]:
!python -m spacy download en

2021-03-30 07:19:26.315098: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
     |████████████████████████████████| 13.7MB 244kB/s 
  Found existing installation: en-core-web-sm 2.2.5
    Uninstalling en-core-web-sm-2.2.5:
      Successfully uninstalled en-core-web-sm-2.2.5
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [9]:
!python -m spacy download en_core_web_sm

2021-03-30 07:19:46.881949: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


# Data Cleaning

In [10]:
import spacy
from spacy import displacy

In [11]:
nlp = spacy.load('en_core_web_sm')

In [12]:

text = "Apple, This is first sentence. and Google this is another one. here 3rd one is"

In [13]:

doc = nlp(text)

In [14]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd one is

In [15]:
for token in doc:
    print(token)


Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
here
3rd
one
is


In [16]:

sent = nlp.create_pipe('sentencizer')


In [17]:

doc = nlp(text)

In [18]:
for sent in doc.sents:
    print(sent)

Apple, This is first sentence.
and Google this is another one.
here 3rd one is


In [19]:
from spacy.lang.en.stop_words import STOP_WORDS

In [20]:
stopwords = list(STOP_WORDS)
print(stopwords)

['across', 'regarding', 'every', 'almost', 'last', 'next', 'onto', 'afterwards', 'whereafter', 'throughout', 'though', 'thereby', 'too', 'before', 'made', 'had', 'it', 'part', 'top', 'then', 'herein', 'will', 'may', 'whom', 'nor', 'either', '’ve', 'must', 'to', 'beforehand', 'meanwhile', 'into', 'seems', 'whether', 'is', 'without', 'after', 'herself', 'mine', 'nine', 'her', 'in', 'only', 'call', 'mostly', 'n‘t', 'sometime', 'yourselves', 'others', 'hereafter', 'anyway', 'among', 'keep', 're', 'does', 'during', 'hereby', 'a', 'behind', '‘s', 'nothing', 'some', 'around', 'since', 'such', 'various', "'re", 'own', 'he', 'but', 'well', 'our', 'anyhow', 'everywhere', 'than', 'as', 'my', 'on', 'from', 'again', 'never', 'we', 'has', 'itself', 'being', 'them', 'no', 'three', 'elsewhere', 'more', 'all', '’m', 'say', '‘re', 'n’t', 'there', 'yours', 'nowhere', 'serious', 'very', 'was', 'besides', 'via', '’d', 'both', 'somehow', 'whose', 'thereafter', 'through', 'of', 'within', 'sixty', 'fifty', 'o

In [21]:

len(stopwords)

326

In [22]:
for token in doc:
    if token.is_stop == False:
        print(token)

Apple
,
sentence
.
Google
.
3rd


# Lemmatization

In [23]:
doc = nlp('run runs running runner')

In [24]:
for lem in doc:
    print(lem.text, lem.lemma_)

run run
runs run
running run
runner runner


# Parts of Speech (POS)

In [25]:
doc = nlp('All is well at your end!')

In [26]:
for token in doc:
    print(token.text, token.pos_)

All DET
is AUX
well ADV
at ADP
your PRON
end NOUN
! PUNCT


In [27]:
displacy.render(doc, style = 'dep',jupyter = True)

# Entity Detection

In [28]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")

In [29]:
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

In [31]:
displacy.render(doc, style = 'ent',jupyter = True)

# Text Classification

In [32]:
import pandas as pd

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [34]:
data_yelp = pd.read_csv('/content/gdrive/MyDrive/datasets/yelp_labelled.txt', sep='\t', header = None)

In [35]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [36]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name

In [37]:
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [39]:
data_yelp.shape

(1000, 2)

In [40]:
data_amazon = pd.read_csv('/content/gdrive/MyDrive/datasets/amazon_cells_labelled.txt', sep = '\t', header = None)
data_amazon.columns = columns_name

In [41]:

data_amazon.head()

Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [42]:
data_amazon.shape

(1000, 2)

In [43]:
data_imdb = pd.read_csv('/content/gdrive/MyDrive/datasets/imdb_labelled.txt', sep = '\t', header = None)


In [44]:
data_imdb.columns = columns_name

In [45]:
data_imdb.shape

(748, 2)

In [46]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [47]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [48]:
data.shape

(2748, 2)

In [49]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [50]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [51]:

data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

# Tokenization

In [52]:
import string

In [53]:
punct = string.punctuation

In [54]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [55]:
def text_data_cleaning(sentence):
    doc = nlp(sentence)
    
    tokens = []
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [56]:

text_data_cleaning("    Hello how are you. Like this video")

['hello', 'like', 'video']

# Vectorization Feature Engineering (TF-IDF)

In [57]:
from sklearn.svm import LinearSVC

In [58]:
tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
classifier = LinearSVC()

In [59]:
X = data['Review']
y = data['Sentiment']

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [61]:
X_train.shape, X_test.shape

((2198,), (550,))

In [62]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [63]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7f27a38a5320>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [64]:
y_pred = clf.predict(X_test)

In [65]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.81      0.80       285
           1       0.79      0.75      0.77       265

    accuracy                           0.79       550
   macro avg       0.79      0.78      0.78       550
weighted avg       0.79      0.79      0.79       550



In [66]:
confusion_matrix(y_test, y_pred)

array([[232,  53],
       [ 65, 200]])

In [67]:

clf.predict(['Wow, this is amzing lesson'])

array([1])

In [68]:
clf.predict(['Wow, this sucks'])

array([0])

In [69]:
clf.predict(['Worth of watching it. Please like it'])

array([1])

In [70]:
clf.predict(['Loved it. amazing'])

array([1])